### ISSUE TITLE
Testing and Logs 

### ISSUE THREAD

**Issue by sasahoo** [jfeliu007/goplantuml#32]
Hi,

First of all this is an excellent go-uml tool. Thanks for this awesome work.

One issue: I generated a puml file. But when I pasted in server, it fails to show any output.
Then I had to change the puml file going through syntax and all to make this work. Is it possible to automate this just as to start a puml server instance locally and run this at once. And if display is failing, what could be the issues? Right now I don't even see any logs either.

Regards,
Sandip

**Comment by jfeliu007** [comment]
Hi, thanks for your feedback. I am trying to understand the issue you are mentioning here. This is not supposed to work as a server, but rather a command or a library you can use for your own projects. When you say you pasted it in the server and it fails to show any output, could you describe this better? Did you use the command or are you using the Parser library?

**Comment by sasahoo** [comment]
Hi, I fully understand. You are right. But there can be some utility to find the issue if it failed to draw the diagram. I am using the command line. `goplantuml -recursive dirpath > file_name.puml`. I setup plantuml server locally by this https://github.com/plantuml/plantuml-server. The server doesnt even provide any logs to find the problem. I am not sure the problem lies with server generating diagram or with the generated file. Thus I thought to capture logs here itself by running through an in-built server.

**Comment by jfeliu007** [comment]
Could you post an example of the kind of diagram that the tool generates that does not work?

**Comment by sasahoo** [comment]
Sure, I will try to mock similar to that generated one and share it here. Meanwhile I have raised an issue of whereabouts of the logs in plantuml-server page.

**Comment by jfeliu007** [comment]
Great. Thanks. If you can also post the source mock it will also help for this issue.

**Comment by jfeliu007** [comment]
This has been here for some time now. I don't think it should be part of this project to provide a server for testing purposes. In regards to logs, the parser tries to return errors whenever possible. I am looking into a way to reduce the amount of incorrect results from the parser at the command line level, not necessarily at the parser level since I'd like the parser to fail when something is wrong. See #60 . I think I will close this one soon, unless there is more discussion on this issue and we can come up with a course of action.
