### ISSUE TITLE
Struct Fields are not part of the diagram

### ISSUE THREAD

**Issue by FabianTe** [jfeliu007/goplantuml#34]
Hi there!

First of all, nice work, like the idea of this repo!

I noticed, that [this code](https://gist.github.com/FabianTe/f16f6f233025fea6eee544597c10ddf8) looks like this:

![image](https://user-images.githubusercontent.com/7669818/66714987-21507180-edbe-11e9-8227-5e9c5aa930e7.png)

But I would have expected something like this:

![image](https://user-images.githubusercontent.com/7669818/66714990-2d3c3380-edbe-11e9-92c1-8b12bc2b63f1.png)

which would correspond to this PlantUML:

```
@startuml
namespace plantuml {
    class Phone << (S,Aquamarine) >> {
        + Value string
        + IsMobile bool

    }
    class Person << (S,Aquamarine) >> {
        + Birthday Birthday
        + Phones []Phone

    }
    class Birthday << (S,Aquamarine) >> {
        + Time time.Time

    }
    Phone <|-- Person
    Birthday <|-- Person
}
@enduml
```

I would like to use this tool to create a quick ERD for an upcoming project. And doing this by code enables me to quickly generate these models.

My proposal:

If displaying links based on struct fields is not considered a standard, could this at least be added as an CLI option?

**Comment by jfeliu007** [comment]
Hi @FabianTe , 
Thanks for the comment.

It looks like maybe aggregation could be the solution for this. Since a person Has-A phone and Has-A Birthday.

Possibly resulting on something like this

@startuml
namespace plantuml {
    class Phone << (S,Aquamarine) >> {
        + Value string
        + IsMobile bool

    }
    class Person << (S,Aquamarine) >> {
        + Birthday Birthday
        + Phones []Phone

    }
    class Birthday << (S,Aquamarine) >> {
        + Time time.Time

    }
    Person o-- Phone
    Person o-- Birthday
}
@enduml

![aggregation](https://user-images.githubusercontent.com/10119160/67051294-b1692080-f108-11e9-9bea-e4c672bb94ec.png)

Is this what you are looking for with this issue? I think I thought of adding this before, but it might have been too clogged for the diagram. If this specific configuration suits you I can definitely consider it as part of the Parser and we can include an option on the CLI. 

If what you are looking for is changing the definition of the <|-- link to mean what you described, then I guess this should entail a longer discussion, since that could alter the meaning of the diagram.

**Comment by FabianTe** [comment]
> Is this what you are looking for with this issue? I think I thought of adding this before, but it might have been too clogged for the diagram. If this specific configuration suits you I can definitely consider it as part of the Parser and we can include an option on the CLI.

Yes

**Comment by jfeliu007** [comment]
Ok, I'll work on this one.

**Comment by jfeliu007** [comment]
Hi @FabianTe 
I made an update to master with this implemented. I will welcome any comments regarding this. Thanks for your suggestion. I will make this part of the next release. But for now, it will be on the master branch only. 

I am thinking of cutting a release in the following days. 
Best regards.

**Comment by FabianTe** [comment]
Thank you! That was really quick, nice.

**Comment by jfeliu007** [comment]
No problems. Thanks for your suggestion. Keep in mind I initially set a flag -aggregation that I quickly deprecated in favor of a different suggestion. 

These are considered aggregations so take a look at the Readme and specifically the usage section, you will see the flag in there ```-show-aggregations```. Let me know if this works for you 👍

**Comment by jfeliu007** [comment]
By the way. This update will only show aggregations for Public fields. I think if we include every field the diagram would be unreadable.
