### ISSUE TITLE
How to generate the UML diagram?

### ISSUE THREAD

**Issue by aggarwalanubhav** [jfeliu007/goplantuml#99]
Hi @jfeliu007, 

I have created the .puml file but I'm not quite getting what command should I run to generate the UML diagram. Please help me with this.

Thanks.

**Comment by jfeliu007** [comment]
You have to use plantuml. Take a look [www.plantuml.com](www.plantuml.com) for options on how to generate an image from the pulm file.

**Comment by jfeliu007** [comment]
@aggarwalanubhav maybe you would be interested in knowing that we made a service that help you generate diagrams. If you have your project in github.com or are interested in reviewing any other public GoLang project, you can use [www.dumels.com](https://www.dumels.com) to generate yours. 😄

**Comment by jasontcole** [comment]
Because I cannot use a public service for private code, I use PlantUML from the Shell like @jfeliu007 mentioned.  It took a bit of digging to figure it out but I end up using something like `cat pumlfile.puml | plantuml.jar java -pipe > imagefile.png`.  Of course, you'll need PlantUML installed. As a side note, add the argument `-DPLANTUML_LIMIT_SIZE=100000` if you have a very large puml or else the image will be cutoff.
